# Generated by Django 3.2.9 on 2021-12-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Flag')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Text classification',
                'verbose_name_plural': 'Texts classifications',
            },
        ),
    ]
