# Generated by Django 3.2.9 on 2021-12-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textclassification',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label predict'),
        ),
    ]
